project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  page-navigation: true
  title: "Estatística Computacional"
  sidebar:
    style: "docked"
    search: false
    logo: img/ESTAT0090_logo_hex.png
    background: "#BED5BE"
    contents:
    - section: "Informações do curso"
      contents: 
      - href: info/dados_gerais.qmd
        text: "Dados gerais"
      - href: info/ementa.qmd
        text: "Ementa e objetivos"
      - href: info/conteudo.qmd
        text: "Conteúdo"
      - href: info/bibliografia.qmd
        text: "Bibliografia"
      - href: info/cronograma.qmd
        text: "Cronograma"
    - section: "Material das aulas"
      contents: 
      - href: conteudos/conteudo1.qmd
        text: "Conteúdo 1"
      - href: conteudos/conteudo2.qmd
        text: "Conteúdo 2"

format:
  html:
    theme: yeti
    toc: true
