project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  page-navigation: true
  title: "Estatística Computacional"
  sidebar:
    style: "docked"
    search: false
    logo: img/ESTAT0090_logo_hex.png
    background: "#BED5BE"
    contents:
    - section: "Informações da disciplina"
      contents: 
      - href: info/dados_gerais.qmd
        text: "Dados gerais"
      - href: info/ementa.qmd
        text: "Ementa e objetivos"
      - href: info/conteudo.qmd
        text: "Conteúdo"
      - href: info/bibliografia.qmd
        text: "Bibliografia"
      - href: info/cronograma.qmd
        text: "Cronograma"
      - href: info/softwares.qmd
        text: "Softwares Necessários"
    - section: "Material das aulas"
      contents: 
      - href: conteudos/1-Apresentacao_da_disciplina.qmd
        text: "1- Apresentação da Disciplina"
      - href: conteudos/2-Introducao_ao_RStudio+GitHub.qmd
        text: "2- Introdução ao RStudio + GitHub"
      - href: conteudos/3-Introducao_ao_LaTeX.qmd
        text: "3- Introdução ao LaTeX"
      - href: conteudos/4-Estrutura_Basica_LaTeX.qmd
        text: "4- Estrutura Básica do LaTeX"
      - href: conteudos/5-Ambiente_Matematico_LaTeX.qmd
        text: "5- Ambiente Matemático no LaTeX"
      - href: conteudos/6-Tabelas-Figuras-Outros-Recursos-LaTeX.qmd
        text: "6- Tabelas, Figuras e Outros Recursos em LaTeX"

format:
  html:
    theme: yeti
    toc: true
    grid:
      sidebar-width: 400px
resources:
  - PDF_slides/**