---
title: ""
format:
  html:
    toc: false
    anchor-sections: false
---

# Conteúdo 3

## Introdução ao LaTeX

Como criar documentos científicos bem formatados, padronizados e prontos para publicação? Esta aula parte dessa questão para apresentar o LaTeX, uma linguagem de marcação voltada à produção de textos técnicos e acadêmicos. A atividade será conduzida de maneira prática, com foco no aprendizado dos comandos básicos de formatação, controle do tamanho da fonte e uso de cores no texto. Ao longo da aula, será possível experimentar o poder do LaTeX para organizar e apresentar conteúdos de forma profissional, desenvolvendo uma habilidade fundamental para a produção de relatórios, artigos e trabalhos em Estatística e Ciência de Dados.

Slides:

- [Versão html](/slides/03-Introducao_ao_LaTeX/03-Introducao_ao_LaTeX.html){target="_blank"}

- [Versão pdf](/PDF_slides/03-Introducao_ao_LaTeX.pdf){target="_blank"}


## Atividade

Reproduza em LaTeX o arquivo [03-Introducao_ao_LaTeX_Atv01.pdf](/PDF_slides/03-Introducao_ao_LaTeX_Atv01.pdf){target="_blank"}.

Algumas configurações utilizadas:

- tamanho da fonte geral: 11pt
- cores: `blue` e `red`
- tamanho da fonte `\scriptsize` e `\Large` em algumas frases