---
title: ""
format:
  html:
    toc: false
    anchor-sections: false
---

# Conteúdo 5

## Ambiente Matemático no LaTeX

Vamos dominar o uso do ambiente matemático no LaTeX para criar equações profissionais em documentos técnicos, aprendendo desde fórmulas simples até estruturas complexas como frações, somatórios e integrais, com numeração automática e referências cruzadas. Descobriremos como formatar símbolos, funções matemáticas e teoremas, garantindo clareza e precisão em artigos, relatórios e apresentações, seguindo os padrões acadêmicos.

Slides:

- [Versão html](/slides/05-Ambiente_Matematico_LaTeX/05-Ambiente-Matematico-LaTeX.html){target="_blank"}

- [Versão pdf](/PDF_slides/05-Ambiente-Matematico-LaTeX.pdf){target="_blank"}


## Dica útil: Detexify

Para quem trabalha com LaTeX e busca agilidade, o Detexify é uma ferramenta indispensável.

Acesse: <https://detexify.kirelabs.org/classify.html>

Este recurso permite que você desenhe um símbolo matemático ou especial diretamente na tela. Em resposta, ele identifica o desenho e sugere os comandos LaTeX correspondentes, otimizando significativamente o processo de inserção de símbolos e aumentando a produtividade.



## Atividade

Reproduza todas as atividades dos slides.