---
title: ""
format:
  html:
    toc: false
    anchor-sections: false
---

## Conteudo

1. Geração de variáveis aleatórias

    1.1. Comandos básicos do R
    
    1.2. Estruturas de repetição no R
    
    1.3. Condições e sı́mbolos lógicos no 
    
    1.4. Escrevendo funções no R
    
    1.5. Gerador de números aleatórios
    
    1.6. Método da Transformada inversa
    
    1.7. Método da Aceitação-Rejeição
    
    1.8. Outros métodos de geração de v.a.

2. Métodos de Monte Carlo

    2.1. Conceito Geral
    
    2.2. Testes de Hipóteses e Erros
    
    2.3. Intervalos de confiança
    
    2.4. Viés e Erro quadrático Médio
    
    2.5. Método de Reamostragem: Bootstrap
    
    2.6. Método de Reamostragem: Jackknife

3. O editor de textos LaTeX

    3.1. Comandos iniciais
    
    3.2. Formatação de texto, Tipos de Listas, Teoremas
    
    3.3. Fórmulas diversas, sı́mbolos matemáticos, escrevendo em ambiente de fórmulas
    
    3.4. Matrizes, equações alinhadas, tabelas e imagens
    
    3.5. Textos sem formatação (Para saı́das computacionais)
    
    3.6. Partes de documento: Tı́tulos, capı́tulos, sumários, cabeçalho e rodapé, bibliografia básica
    
    3.7. BibTeX (bibliografia externa)
    
    3.8. Criando Apresentações e Pôster