---
title: ""
format:
  html:
    toc: false
    anchor-sections: false
---

## Dados Gerais da Disciplina

**Componente curricular:**  
**ESTAT0090 - Estatística Computacional**  
*Disciplina obrigatória para o curso de Estatística da Universidade Federal de Sergipe*


## Informações da Disciplina

- **Carga Horária:** 60 horas (4 créditos)
- **Unidade Responsável:** Departamento de Estatística e Ciências Atuariais (DECAT)
- **Docente Responsável:** Prof. Dr. Sadraque E. F. Lucena
- **Período Letivo:** 2025-1
- **Plano de Ensino da Disciplina:**  [pdf](/PDF_slides/plano_de_ensino_estatistica_computacional.pdf){target="_blank"}


## Horários das Aulas

As aulas ocorrerão nos seguintes horários:

- **Terças**: 19h00 às 20h30 no LEA01 (Laboratório de Informática 01 do DECAT)
- **Quintas**: 20h45 às 22h15 no LEA02 (Laboratório de Informática 02 do DECAT)




## Avaliações

A disciplina contará com **3 avaliações** distribuídas ao longo do semestre nas seguintes datas:

- **Avaliação 1:** 17/06/2025 (terça)
- **Avaliação 2:** 29/07/2025 (terça)
- **Avaliação 3:** 02/09/2025 (terça)


## Não haverá aula

- **19/06/2025:** Corpus Christi (ponto facultativo)
- **24/06/2025:** Sâo João (feriado municipal)
- **08/07/2025:** Independência de Sergipe (feriado estadual)